# Generated by Django 4.2.3 on 2023-08-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverify",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "Create Account"),
                    ("1", "Change Password"),
                    ("2", "Change Information"),
                ],
                default="0",
                help_text="Types of token",
                max_length=1,
            ),
        ),
    ]
