# Generated by Django 4.2.3 on 2023-07-18 08:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pitch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=1000, null=True)),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[("1", "Pitch 5"), ("2", "Pitch 7"), ("3", "Pitch 12")],
                        default="1",
                        help_text="Types of football fields",
                        max_length=1,
                    ),
                ),
                (
                    "surface",
                    models.CharField(
                        blank=True,
                        choices=[("a", "Artificial"), ("n", "Natural"), ("m", "Mixed")],
                        default="n",
                        help_text="Types of surface grass",
                        max_length=1,
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(2000000000),
                            django.core.validators.MinValueValidator(0),
                        ]
                    ),
                ),
            ],
            options={
                "ordering": ["price", "size"],
            },
        ),
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "min_cost",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(20000000),
                            django.core.validators.MinValueValidator(0),
                        ]
                    ),
                ),
                (
                    "discount",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(200000000),
                            django.core.validators.MinValueValidator(0),
                        ]
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(200000),
                            django.core.validators.MinValueValidator(1),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_start", models.DateTimeField(auto_now_add=True)),
                ("time_end", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("o", "Ordered"),
                            ("d", "Cancelled"),
                            ("c", "Confirmed"),
                        ],
                        default="n",
                        help_text="Types of surface grass",
                        max_length=1,
                    ),
                ),
                (
                    "cost",
                    models.PositiveBigIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(20000000000),
                            django.core.validators.MinValueValidator(0),
                        ]
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "renter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pitch.voucher"
                    ),
                ),
            ],
            options={
                "ordering": ["created_date", "cost"],
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        help_text="Enter a link of image (e.g.Science Fiction)",
                        max_length=500,
                    ),
                ),
                (
                    "pitch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pitch.pitch"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                ("comment", models.CharField(max_length=500)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "pitch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pitch.pitch"
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_date"],
            },
        ),
    ]
