# Generated by Django 4.2.3 on 2023-07-19 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pitch", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="comment",
            table="comments",
        ),
        migrations.AlterModelTable(
            name="image",
            table="images",
        ),
        migrations.AlterModelTable(
            name="order",
            table="orders",
        ),
        migrations.AlterModelTable(
            name="pitch",
            table="pitches",
        ),
        migrations.AlterModelTable(
            name="voucher",
            table="vouchers",
        ),
    ]
