# Generated by Django 4.2.3 on 2023-08-21 03:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pitch", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="pitch.comment",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="time_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 21, 3, 27, 23, 853724, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="time_start",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 21, 3, 27, 23, 853710, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
