# Generated by Django 4.2.3 on 2023-08-03 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 10, 20, 27, 776167, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 10, 20, 27, 776167, tzinfo=datetime.timezone.utc)),
        ),
    ]
