# Generated by Django 4.2.3 on 2023-07-24 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pitch", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("o", "Ordered"), ("d", "Cancelled"), ("c", "Confirmed")],
                default="o",
                help_text="Types of surface grass",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="time_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 24, 4, 1, 6, 497926, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="time_start",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 24, 4, 1, 6, 497912, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
