# Generated by Django 4.2.3 on 2023-07-19 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pitch", "0002_alter_comment_table_alter_image_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(2000000000),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="pitch",
            name="avg_rating",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=3,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="pitch",
            name="phone",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
