# Generated by Django 4.2.3 on 2023-08-08 09:30

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pitch', '0002_alter_order_time_end_alter_order_time_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitch',
            name='avg_rating',
        ),
        migrations.AlterField(
            model_name='order',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 9, 30, 38, 679761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 9, 30, 38, 679761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='PitchRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('count_comment', models.PositiveIntegerField(default=0)),
                ('pitch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pitch_rating', to='pitch.pitch')),
            ],
        ),
        migrations.CreateModel(
            name='AccessComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_comment_created', models.PositiveIntegerField(default=0)),
                ('count_comment_updated', models.PositiveIntegerField(default=0)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitch.pitch')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('renter', 'pitch')},
            },
        ),
    ]
