# Generated by Django 4.2.3 on 2023-07-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pitch", "0003_order_price_pitch_avg_rating_pitch_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="link",
        ),
        migrations.AddField(
            model_name="image",
            name="image",
            field=models.ImageField(
                default="default-image.jpg",
                help_text="Image of the pitch",
                upload_to="uploads/",
            ),
        ),
    ]
