# Generated by Django 4.2.3 on 2023-07-20 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pitch", "0004_remove_image_link_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="pitch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="pitch.pitch",
            ),
        ),
    ]
